# Generated by Django 4.2.3 on 2023-08-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusform',
            name='is_read_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
