# Generated by Django 4.2.3 on 2023-08-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_rename_title_contactusform_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUsForm',
            new_name='ContactUsMessage',
        ),
    ]
